language: node_js
env:
  global:
    - GH_REF: github.com/w3c/wcag21.git
    - secure: "VgTeV60bxyW04kTJ08qriNj465VqW9VmX4uvvVNB8Kyc9JYHn8BeSTLLbldb1fpoLdmqDstZFYaqIj4YkyrwdYoJUuLWNW4az2/w27RS4WLxyYW6pJyry0XLmvuRkR/fvOs28JjNAPwjLl2yTVjEhrpYIStXb876VDC+UQU8baNHpS0wBvL3wgpElR37lARnmfciNQ96M8daMOIAKht5fWQ422P2rZNpbigNe8EysDuXM77MkEOk9iZ0W0I1UC790imkvEV3rYJneteeq9+I4VeR2BpUv3crBjgJiBIdF9Vz3SG6dyxea+faoCzjcxJ/J6Wbwzla7Eoe4j0CZHXgVk01oKYlgCCu7MktsZemcBwIrnHZHvYIbD1MLvYpMHXr8VDo81dQwln3zUZJ2oBJOd4F7gANKDOtDHsbMRtaFBaKhnaN8RU58KLAPzjgi2Xp2Vg8SRCDJGMS9NQQmuSJZ5Tug+zY4J5BNFKazOV+aRrPXoroIKxAqJSJUPFKgoAD6eowVQboriMkg0OG9H8JxkqLmC1UrPhtQFext9ya7CYImFhX+mI0l93W1Catqw/R8KJIhHPzEpGzlUfCXynBiXxX9EIFJmmMft3jiYyfT8EynM6W89z2LL+PKTt6m1vdyhXHtyZdZgJZezXcck4IqVeaOPkC+FyWkR55NNK7G1s="
    
git:
  depth: 3
  
branches:
  only:
    master

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"
  
script:
  - cd ../..
  - mkdir gh-pages
  - cd gh-pages
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/wcag21.git
  - cd wcag21
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/wcag21/master/requirements/index.html -o requirements/index.html -f

after_success:
  - git add -A .
  - git commit -m "Generated by TRAVIS-CI"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages
