name: CI

# Reference documentation: https://docs.github.com/en/actions/reference

# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    branches: [main]

jobs:
  build-xslt:
    name: run xslt-based generator
    runs-on: ubuntu-20.04
    env:
      GH_REF: github.com/w3c/wcag.git
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Java
        # see https://github.com/actions/setup-java#supported-distributions
        # note that this also deploys ant
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: before_install
        run: |
          tar -xzvf lib/apache-ant-1.10.6-bin.tar.gz
          export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH
      - name: script
        run: |
          mkdir output
          git clone --depth=1 --branch=gh-pages https://github.com/w3c/wcag.git output
          ant deploy
  build-spec:
    name: run spec-prod based build
    runs-on: ubuntu-20.04
    env:
      GH_REF: github.com/w3c/wcag.git
    needs: build-xslt
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source: guidelines/index.html
            destination: output/guidelines/22/index.html
          - source: requirements/22/index.html
            destination: output/requirements/22/index.html
          - source: conformance-challenges/index.html
            destination: output/conformance-challenges/index.html
        steps:
          - uses: actions/checkout@v2
          - uses: w3c/spec-prod@v2
            with:
              SOURCE: ${{ matrix.source }}
              DESTINATION: ${{ matrix.destination }}
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    env:
      GH_REF: github.com/w3c/wcag.git
      BRANCH: gh-pages
      LOCAL_DIR: output
      GITHUB_TOKEN: ${{ secrets.W3CGRUNTBOT_TOKEN }}
    needs: build-spec
    run: .github/scripts/deploy.sh

