name: "Update Pull Request with Preview Link"

on: pull_request

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        head-branch-regex: '.*'
        title-template: ''
        body-template: '[Preview Changes](https://raw.githack.com/w3c/wcag/%headbranch%/guidelines/index.html)'
        body-update-action: prefix
        body-uppercase-head-match: false
